/*    ==Scripting Parameters==

    Source Server Version : SQL Server 2016 (13.0.4001)
    Source Database Engine Edition : Microsoft SQL Server Express Edition
    Source Database Engine Type : Standalone SQL Server

    Target Server Version : SQL Server 2016
    Target Database Engine Edition : Microsoft SQL Server Express Edition
    Target Database Engine Type : Standalone SQL Server
*/

USE [master]
GO

/****** Object:  Database [Teacher]    Script Date: 11/20/2017 10:21:29 AM ******/
CREATE DATABASE [Teacher]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Teacher', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\Teacher.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Teacher_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\Teacher_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Teacher] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Teacher].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Teacher] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Teacher] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Teacher] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Teacher] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Teacher] SET ARITHABORT OFF 
GO

ALTER DATABASE [Teacher] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Teacher] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Teacher] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Teacher] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Teacher] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Teacher] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Teacher] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Teacher] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Teacher] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Teacher] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Teacher] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Teacher] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Teacher] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Teacher] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Teacher] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Teacher] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Teacher] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Teacher] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Teacher] SET  MULTI_USER 
GO

ALTER DATABASE [Teacher] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Teacher] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Teacher] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Teacher] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Teacher] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Teacher] SET QUERY_STORE = OFF
GO

USE [Teacher]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [Teacher] SET  READ_WRITE 
GO

